### ISSUE TITLE
please clarify license for source repo

### ISSUE THREAD

**Issue by tastratton** [Shoeib-Yarmand/Json-repository-configuration#1]
It appears that the nuget package uses MIT license.  
Thank you for contributing to open source!
https://www.nuget.org/packages/JsonRepositoryConfiguration

Is the source also MIT license?

[stackexchange - does nuget package license equal source code license](https://softwareengineering.stackexchange.com/questions/233339/are-nuget-metadata-a-good-place-to-exclusively-set-license-for-source-code)

[github - add a license to repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by Benji-Yarmand** [comment]
Hi,

Thanks for reaching out. 

I cannot confirm that at this time, as I need to conduct the same level of scrutiny first.
